---
title: "STAT 429 Report"
author: "Andrew, Joseph, Jonathan"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
df <- read.csv("PSID1976.csv")

df$participation[df$participation=="no"]<-0
df$participation[df$participation=="yes"]<-1
df$city[df$city=="no"]<-0
df$city[df$city=="yes"]<-1
df$college[df$college=="no"]<-0
df$college[df$college=="yes"]<-1
df$hcollege[df$hcollege=="no"]<-0
df$hcollege[df$hcollege=="yes"]<-1

df<-transform(df, participation = as.integer(participation),city = as.integer(city), college= as.integer(college), hcollege=as.integer(hcollege))
df
```
```{r}

nrow(df)
ncol(df)
range(df$participation)
range(df$youngkids)
range(df$oldkids)
range(df$age)
range(df$education)
range(df$hhours)
range(df$hage)
range(df$heducation)
range(df$hwage)
range(df$fincome)
range(df$tax)
range(df$meducation)
range(df$feducation)
range(df$unemp)
range(df$city)
range(df$experience)
range(df$college)
range(df$hcollege)
```


```{r}
library(car)
m1<-glm(df$participation~youngkids+oldkids+age+education+hhours+hage+heducation+hwage+fincome+tax+meducation+feducation+unemp+experience+city+college+hcollege, family="binomial",data=df)
summary(m1)
```

```{r}
mmp(m1)
```

```{r}
backwardBIC=step(m1, direction = "backward", k=log(n))
```

```{r}

m2 <- glm(df$participation~oldkids+education+hhours+youngkids+age+hwage+tax+experience, family="binomial",data=df)
summary(m2)
```

```{r}
mmps(m2)
```

```{r}
anova(m1,m2, test="Chisq")
```
```{r}
## Mean of each predictor variable in m2
x<-c(1, mean(df$oldkids), mean(df$education), mean(df$hhours), mean(df$youngkids), mean(df$age), mean(df$hwage), mean(df$tax), mean(df$experience))

## Probability of success
p<-exp(sum(coef(m2)*x))/(1+exp(sum(coef(m2)*x)))
p

## Calculation for logit using the probability of success
logOdds<-log(p/(1-p))
logOdds

## Or
## Another way to calculate logit
AlsologOdds<-sum(coef(m2)*x)
AlsologOdds

""
coef(m2)

##  if the number of children in the household with ages between 6 and 18 increased by 1 then the odds in favor for the individual to participate in the labor force in 1975 will change by a multiplicative factor of.. 
m2$coefficients[2]; exp(m2$coefficients[2]) 
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
